services:
  mon-site:
    build: .
    container_name: site-bmax
    restart: always
    ports:
      - "3000:8000"
    environment:
      - NODE_ENV=production

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
